const {
  deviceAllAccess,
  deviceAllWeatherData,
  deviceAllDiagnosticsData,
  userAllPeoplesMetrics,
  deviceAllStatus,
  deviceDScopeAllStatus,
  deviceAllFiberAligner,
  deviceAllPowerCableTesters,
  deviceAllAr,
  deviceAllAc,
  deviceAllGeyserSettings,
  usersAttachGeyserDevice,
  deviceAllOTA,
  debugV0,
  debugVP,
  printLabel,
  deviceAllNetworksList,
  deviceAllConfigAdmin,
  deviceAllGps,
  deviceFiberAlignerImageData,
  deviceFiberAlignerData,
  deviceUserLogin,
  deviceAllTransactionalLogs,
  deviceAllHTT,
  userAllNotifications,
  deviceConfigsRevised,
  trolleyTrackingLocalStatus,
  deviceUpdateVersion,
  deviceUpdateNew,
  deviceSetTankData,
  deviceSetEnergyData,
  deviceDScopeData,
  updateProductTracker,
  removeDeviceData,
} = require("./messageHandlers");

exports.mqttChannels = [
  {
    name: "DEVICE_ALL_ACCESS",
    channel: "d/+/access",
    regex: /d\/[0-9]+\/access/i,
    handler: deviceAllAccess,
  },
  {
    name: "DEVICE_ALL_WEATHER_DATA",
    channel: "d/+/wd",
    regex: /d\/[0-9]+\/wd/i,
    handler: deviceAllWeatherData,
  },
  {
    name: "USER_ALL_PEOPLE_METRICS",
    channel: "u/+/pm",
    regex: /^u\/[0-9]+\/pm$/i,
    handler: userAllPeoplesMetrics,
  },
  {
    name: "DEVICE_ALL_STATUS",
    channel: "d/+/status",
    regex: /^(d|s)\/[0-9a-z-:]+(\/bd)?\/status$/i,
    handler: deviceAllStatus,
  },
  {
    name: "DEVICE_ALL_DSCOPE_STATUS",
    channel: "d/+/dscope/status",
    regex: /d\/[0-9]+\/dscope\/status/i,
    handler: deviceDScopeAllStatus,
  },
  {
    name: "DEVICE_ALL_FIBER_ALIGNER",
    channel: "d/+/fb",
    regex: /^d\/[\S]*\/fb$/i,
    handler: deviceAllFiberAligner,
  },
  {
    name: "DEVICE_ALL_POWER_CABLE_TESTER",
    channel: "d/+/pct",
    regex: /^d\/[0-9]+\/pct$/i,
    handler: deviceAllPowerCableTesters,
  },
  {
    name: "DEVICE_ALL_AR",
    channel: "d/+/ar",
    regex: /^d\/[0-9]+\/ar$/i,
    handler: deviceAllAr,
  },
  {
    name: "DEVICE_ALL_AC",
    channel: "d/+/ac",
    regex: /^d\/[0-9]+\/ac$/i,
    handler: deviceAllAc,
  },
  {
    name: "DEVICE_ALL_GEYSER_SETTINGS",
    channel: "d/+/gs/ss",
    regex: /d\/[0-9]+\/gs\/ss/i,
    handler: deviceAllGeyserSettings,
  },
  {
    name: "USERS_ALL_GEYSER_DEVICE",
    channel: "user/+/gs/d/#",
    regex: /user\/[0-9]+\/gs\/d\//i,
    handler: usersAttachGeyserDevice,
  },
  {
    name: "DEVICE_ALL_OTA",
    channel: "d/+/ota",
    regex: /d\/[0-9]+\/ota/i,
    handler: deviceAllOTA,
  },
  {
    name: "DEBUG_V0_LOGS",
    channel: "debugv0",
    regex: /debugv0/i,
    handler: debugV0,
  },
  {
    name: "DEBUG_VP_LOGS",
    channel: "debugvp",
    regex: /debugvp/i,
    handler: debugVP,
  },
  {
    name: "PRINT_LABEL",
    channel: "printlabel",
    regex: /printlabel/i,
    handler: printLabel,
  },
  {
    name: "DEVICE_ALL_NETWORK_LIST",
    channel: "d/+/network/list",
    regex: /d\/[0-9]+\/network\/list/i,
    handler: deviceAllNetworksList,
  },
  {
    name: "DEVICE_ALL_CONFIG_ADMIN",
    channel: "d/+/config/admin",
    regex: /d\/[0-9]+\/config\/admin/i,
    handler: deviceAllConfigAdmin,
  },
  {
    name: "DEVICE_ALL_GPS",
    channel: "d/+/gps",
    regex: /d\/[0-9]+\/gps/i,
    handler: deviceAllGps,
  },
  {
    name: "DEVICE_ALL_FIBER_ALIGNER_IMAGE_DATA",
    channel: "d/+/faid",
    regex: /^d\/[0-9]+\/faid$/i,
    handler: deviceFiberAlignerImageData,
  },
  {
    name: "DEVICE_ALL_FIBER_ALIGNER_DATA",
    channel: "d/+/fad",
    regex: /^d\/[0-9]+\/fad$/i,
    handler: deviceFiberAlignerData,
  },
  {
    name: "DEVICE_ALL_LOGIN",
    channel: "d/+/login",
    regex: /^d\/[0-9]+\/login$/i,
    handler: deviceUserLogin,
  },
  {
    name: "DEVICE_ALL_DIAGNOSTIC_DATA",
    channel: "d/+/diagnostic_data",
    regex: /d\/[0-9]+\/diagnostic_data/i,
    handler: deviceAllDiagnosticsData,
  },
  {
    name: "DEVICE_ALL_TRANSACTIONAL_LOGS",
    channel: "d/+/tlog/#",
    regex: /d\/[0-9]+\/tlog\//i,
    handler: deviceAllTransactionalLogs,
  },
  {
    name: "DEVICE_ALL_HTT",
    channel: "d/+/HTT",
    regex: /^d\/[0-9]+\/HTT$/i,
    handler: deviceAllHTT,
  },
  {
    name: "USER_ALL_NOTICES",
    channel: "u/+/notices",
    regex: /u\/[0-9]+\/notices/i,
    handler: userAllNotifications,
  },
  {
    name: "PRODUCT_TRACKER_UPDATE",
    channel: "s/#",
    regex: /^s\/[0-9]+\/bd$/i,
    handler: updateProductTracker,
  },
  {
    name: "DEVICE_ALL_CONFIG_REVISED",
    channel: "d/+/config/revised",
    regex: /^d\/[0-9]+\/config\/revised$/i,
    handler: deviceConfigsRevised,
  },
  {
    name: "TROLLEY_TRACKING_LOCAL_STATUS",
    channel: "tts/local/status",
    regex: /tts\/local\/status/i,
    handler: trolleyTrackingLocalStatus,
  },
  {
    name: "DEVICE_ALL_VERSIONS",
    channel: "d/+/versions",
    regex: /^d\/[0-9]+\/versions$/i,
    handler: deviceUpdateVersion,
  },
  {
    name: "DEVICE_ALL_NEW",
    channel: "d/+/nw",
    regex: /^d\/[0-9]+\/nw$/i,
    handler: deviceUpdateNew,
  },
  {
    name: "DEVICE_ALL_TANK_DATA",
    channel: "d/+/tank_data",
    regex: /d\/[0-9]+\/tank_data/i,
    handler: deviceSetTankData,
  },
  {
    name: "DEVICE_ALL_ENERGY_DATA",
    channel: "d/+/energy_data",
    regex: /d\/[0-9]+\/energy_data/i,
    handler: deviceSetEnergyData,
  },
  {
    name: "DEVICE_ALL_DR",
    channel: "d/+/dr",
    regex: /d\/[0-9]+\/dr/i,
    handler: deviceDScopeData,
  },
  {
    name: "REMOVE_DATA_SSH",
    channel: "d/+/sshdata",
    regex: /d\/[0-9]+\/[a-z0-9-]+\/sshdata/i,
    handler: removeDeviceData,
  },
];
