name: "AWS login configuration for deployment"
description: "LOGIN"
inputs:
  awsAccessKeyId: # id of input
    required: true
  awsSecretAccessKey:
    required: true
  awsRegion:
    required: true
outputs:
  registry:
    description: "Elastic Container Registry Id"
    value: ${{ steps.login-ecr.outputs.registry }}
runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.awsAccessKeyId }}
        aws-secret-access-key: ${{ inputs.awsSecretAccessKey }}
        aws-region: ${{ inputs.awsRegion }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
