name: "workflow"

"on":
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: "Continuous Integration"
    uses: "./.github/workflows/ci-reusable.yml"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
