name: "workflow"

"on":
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: "Continuous Integration"
    uses: "./.github/workflows/ci-reusable.yml"
    secrets:
      GITLAB_AUTH_TOKEN: ${{ secrets.GITLAB_AUTH_TOKEN }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
