name: "Development Deployment"

"on":
  push:
    branches:
      - feat/ci-cd
  workflow_run:
    workflows: ["linting and testing"]

jobs:
  deployment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: "Continuous Deployment"
    uses: "./.github/workflows/cd.yml"
    with:
      IMAGE_TAG: latest
      DOCKER_FILE: Dockerfile
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      ECS_SERVICE: ${{secrets.ECS_SERVICE_DEVELOPMENT}}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
      ECS_TASK_DEFINITION: ${{secrets.ECS_TASK_DEFINITION_DEVELOPMENT}}
      ECS_CONTAINER_NAME: ${{secrets.ECS_CONTAINER_NAME_DEVELOPMENT}}
