# name: "workflow"

# 'on':
#   push:
#     branches:
#       - main
#     tags:
#       - "*"
#   pull_request:
#     branches:
#       - main

# jobs:
#   integration:
#     name: "Continuous Integration"
#     uses: "./.github/workflows/ci.yml"
#     secrets: inherit
#   deployment:
#     if: ${{ github.event_name != 'pull_request' }}
#     needs: integration
#     name: "Continuous Deployment"
#     uses: "./.github/workflows/cd.yml"
#     with:
#       IMAGE_TAG: ${{ (github.ref == 'refs/heads/master' && 'latest') || github.ref_name }}
#       DOCKER_FILE: ${{ (github.ref == 'refs/heads/master' && 'Dockerfile.dev') || 'Dockerfile' }}
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#       AWS_REGION: ${{ secrets.AWS_REGION }}
#       ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
#       ECS_SERVICE: ${{ ((github.ref == 'refs/heads/master') && secrets.ECS_SERVICE_DEVELOPMENT )  || (startsWith(github.ref, 'refs/tags') && secrets.ECS_SERVICE_STAGING) }}
#       ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
#       ECS_TASK_DEFINITION: ${{ ((github.ref == 'refs/heads/master') && secrets.ECS_TASK_DEFINITION_DEVELOPMENT )  || (startsWith(github.ref, 'refs/tags') && secrets.ECS_TASK_DEFINITION_STAGING) }}
#       ECS_CONTAINER_NAME: ${{ ((github.ref == 'refs/heads/master') && secrets.ECS_CONTAINER_NAME_DEVELOPMENT )  || (startsWith(github.ref, 'refs/tags') && secrets.ECS_CONTAINER_NAME_STAGING) }}

