name: "workflow"

"on":
  push:
    branches:
      - main

jobs:
  integration:
    name: "Continuous Integration"
    uses: "./.github/workflows/ci-reusable.yml"
    secrets: inherit
  dev-deployment:
    name: "Dev Deployment"
    needs: integration
    uses: "./.github/workflows/cd-reusable.yml"
    with:
      IMAGE_TAG: "latest"
      DOCKER_FILE: "Dockerfile"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      ECS_SERVICE: ${{ secrets.ECS_SERVICE_DEVELOPMENT }}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
      ECS_TASK_DEFINITION: ${{  secrets.ECS_TASK_DEFINITION_DEVELOPMENT }}
      ECS_CONTAINER_NAME: ${{ secrets.ECS_CONTAINER_NAME_DEVELOPMENT  }}
      GITLAB_AUTH_TOKEN: ${{ secrets.GITLAB_AUTH_TOKEN }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
