name: linting and testing - reusable
on:
  workflow_call:
    secrets:
      VEETECH_GITHUB_AUTH_TOKEN:
        required: true
      AUTH_TOKEN:
        required: true
env:
  VEETECH_GITHUB_AUTH_TOKEN: ${{ secrets.VEETECH_GITHUB_AUTH_TOKEN }}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 16
          submodules: "recursive"
          token: ${{ secrets.AUTH_TOKEN }}
      - run: npm ci
      - run: npm run lint

  testing:
    runs-on: ubuntu-latest
    container: node:16
    services:
      mysql:
        image: public.ecr.aws/t8d8f5a3/mysql:latest
        env:
          MYSQL_USER: user
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
      influxdb:
        image: influxdb:2.6-alpine
        env:
          DOCKER_INFLUXDB_INIT_USERNAME: influxdb
          DOCKER_INFLUXDB_INIT_PASSWORD: influxdb-pwd
          DOCKER_INFLUXDB_INIT_ORG: test
          DOCKER_INFLUXDB_INIT_BUCKET: test
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: aGkcV533WlQq1_ShozzRcxr0ze-k0T_8c04wuq_O-Cdqooo0uNKoDO44WzDNsB0ZY2QgQcUAORg14W3yV1QVPw==
          DOCKER_INFLUXDB_INIT_MODE: setup
        ports:
          - 8086:8086
    strategy:
      fail-fast: false
      matrix:
        ci_index: [0, 1, 2, 3, 4, 5]
        ci_total: [6]
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.AUTH_TOKEN }}
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: set the env variables
        run: echo "${{ vars.TEST_ENV }}" > ".env"

      - name: Install packages
        run: |
          apt update
          apt install jq -y
          apt install findutils -y

      - name: testing
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          CI_NODE_TOTAL: ${{ matrix.ci_total }}
          CI_NODE_INDEX: ${{ matrix.ci_index }}
        run: |
          chmod -R 777 .
          chmod -R 777 ./public
          npm ci --progress=false
          npm run influx-setup
          bash parallel-test.sh $CI_NODE_TOTAL $CI_NODE_INDEX
