name: "workflow"

"on":
  push:
    tags:
      - "*"

jobs:
  tag-validation:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Tag validation
        uses: "./.github/actions/tag-validation.yml"
  integration:
    needs: tag-validation
    name: linting and testing
    uses: "./.github/workflows/ci-reusable.yml"
    secrets: inherit
  stage-deployment:
    name: "Stage Deployment"
    needs: integration
    uses: "./.github/workflows/cd-reusable.yml"
    with:
      IMAGE_TAG: "latest"
      DOCKER_FILE: "Dockerfile"
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      ECS_SERVICE: ${{ secrets.ECS_SERVICE_STAGING }}
      ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}
      ECS_TASK_DEFINITION: ${{  secrets.ECS_TASK_DEFINITION_STAGING }}
      ECS_CONTAINER_NAME: ${{ secrets.ECS_CONTAINER_NAME_STAGING  }}
      GITLAB_AUTH_TOKEN: ${{ secrets.GITLAB_AUTH_TOKEN }}
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
